package com.bukkit.happo2000.BlastControl;

public enum EnumCreeperSetting
{
	DISABLED_WITH_FANGS,
	DISABLED_WITH_DESPAWN,
	DISABLED_ONLY_ENTITY,
	DISABLED,
	LIMITED_WITH_FANGS,
	LIMITED_WITH_DESPAWN,
	LIMITED_ONLY_ENTITY,
	LIMITED,
	ENABLED
}
